"use client"
import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from "./context/AuthContext";
import { ApolloProvider } from "@apollo/client";
import client from "./lib/aplloClient";


 const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">
       <ApolloProvider client={client}>
      <AuthProvider>
       
         <body>
         {children}
         </body>
         
      </AuthProvider>
      </ApolloProvider>

    </html>
  );
}
